module.exports  = {

	SELECT_TEAMS  : 'SELECT TeamID as id, TeamAbbrev as name FROM teams WHERE TeamActive = 1;',

	SELECT_GROUNDS : 'SELECT GroundID as id, GroundAbbrev as name FROM grounds WHERE GroundActive = 1;',

	SELECT_SEASONS : 'SELECT SeasonID as season_id, seasonLeague as season_league, SeasonYear as year, LeagueName as league_name FROM seasons INNER JOIN leaguemanagement ON leaguemanagement.LeagueID = seasons.SeasonLeague ORDER BY SeasonYear DESC, LeagueName DESC;',
	
	SELECT_CURRENT_SEASONS : 'SELECT SeasonID as season_id, seasonLeague as season_league, SeasonYear as year, LeagueName as league_name FROM seasons INNER JOIN leaguemanagement ON leaguemanagement.LeagueID = seasons.SeasonLeague WHERE SeasonYear = YEAR(CURDATE());',

	//SELECT_SEASONS_BY_YEAR : 'SELECT SeasonID as season_id, seasonLeague as season_league, SeasonYear as year, LeagueName as league_name FROM seasons INNER JOIN leaguemanagement ON leaguemanagement.LeagueID = seasons.SeasonLeague WHERE SeasonYear = ?;',

	SELECT_FIXTURES : 'SELECT season as season_id, week, date, hometeam as home_team, awayteam as away_team, venue as ground_id FROM schedule WHERE (season = ? OR season = ?) AND (awayteam = ? OR hometeam = ?) AND date >= CURDATE() ORDER BY date ASC;',

	SELECT_RESULTS : 'SELECT game_date, result FROM scorecard_game_details WHERE (hometeam = ? OR awayteam = ?) AND (season = ? OR season = ?) ORDER BY game_date DESC LIMIT 3;',

	SELECT_STANDINGS : 'SELECT season as season_id, conference as conference_id, LeagueAbbrev as league_name, team as team_id, won, tied, lost, totalpoints as total_points, manualrank as manual_rank FROM ladder INNER JOIN seasons ON seasons.SeasonID = ladder.season INNER JOIN leaguemanagement ON leaguemanagement.LeagueID = seasons.SeasonLeague WHERE season in (SELECT SeasonID FROM seasons INNER JOIN leaguemanagement ON leaguemanagement.LeagueID = seasons.SeasonLeague WHERE SeasonYear = YEAR(CURDATE())) AND conference in (SELECT ConferenceID FROM conferencemanagement) ORDER BY season_id, conference_id, totalpoints DESC;',

	SELECT_ALL_PLAYERS : 'SELECT PlayerID as id, PlayerFName as first_name, PlayerLName as last_name, picture as photo, isactive as is_active, BattingStyle as batting_style, BowlingStyle as bowling_style FROM players WHERE PlayerTeam = ? ORDER BY PlayerFName ASC;',

	//SELECT_PLAYER : 'SELECT PlayerID as id, PlayerFName as first_name, PlayerLName as last_name, picture as photo, BattingStyle as batting_style, BowlingStyle as bowling_style FROM players WHERE PlayerID = ?;',

	SELECT_ALL_BATTING_DETAILS : 'SELECT PlayerID as id, players.PlayerFName as first_name, players.PlayerLName as last_name, picture as photo, isactive as is_active, COUNT(runs) as innings, SUM(notout) as not_out, SUM(scorecard_batting_details.runs) as runs, sum(scorecard_batting_details.balls) as balls, MAX(runs) as highest, COUNT(CASE WHEN scorecard_batting_details.runs >= 100 THEN scorecard_batting_details.runs END) as hundreds, COUNT(CASE WHEN scorecard_batting_details.runs >= 50 AND scorecard_batting_details.runs < 100 THEN scorecard_batting_details.runs END) as fifties,  sum(scorecard_batting_details.fours) as fours, sum(scorecard_batting_details.sixes) as sixes FROM scorecard_batting_details INNER JOIN players ON players.PlayerID = scorecard_batting_details.player_id WHERE player_id in (SELECT PlayerID as id FROM players WHERE PlayerTeam = ?) GROUP BY PlayerID ORDER BY sum(scorecard_batting_details.runs) DESC;',

	SELECT_ALL_BOWLING_DETAILS : 'SELECT PlayerID as id, players.PlayerFName as first_name, players.PlayerLName as last_name, picture as photo, isactive as is_active, sum(scorecard_bowling_details.overs) as overs, sum(scorecard_bowling_details.maidens) as maidens, sum(scorecard_bowling_details.runs) as runs, sum(scorecard_bowling_details.wickets) as wickets, sum(scorecard_bowling_details.noballs) as no_balls, sum(scorecard_bowling_details.wides) as wides FROM scorecard_bowling_details INNER JOIN players ON players.PlayerID = scorecard_bowling_details.player_id WHERE player_id in (SELECT PlayerID as id FROM players WHERE PlayerTeam = ? ) GROUP BY PlayerID ORDER BY sum(scorecard_bowling_details.wickets) DESC;',

	SELECT_CURRENT_BATTING_DETAILS : 'SELECT PlayerID as id, players.PlayerFName as first_name, players.PlayerLName as last_name, picture as photo, isactive as is_active, COUNT(runs) as innings, SUM(notout) as not_out, SUM(scorecard_batting_details.runs) as runs, sum(scorecard_batting_details.balls) as balls, MAX(runs) as highest, COUNT(CASE WHEN scorecard_batting_details.runs >= 100 THEN scorecard_batting_details.runs END) as hundreds, COUNT(CASE WHEN scorecard_batting_details.runs >= 50 AND scorecard_batting_details.runs < 100 THEN scorecard_batting_details.runs END) as fifties,  sum(scorecard_batting_details.fours) as fours, sum(scorecard_batting_details.sixes) as sixes FROM scorecard_batting_details INNER JOIN players ON players.PlayerID = scorecard_batting_details.player_id WHERE player_id in (SELECT PlayerID as id FROM players WHERE PlayerTeam = ?) AND season in (SELECT SeasonID FROM seasons WHERE SeasonYear = YEAR(CURDATE())) GROUP BY PlayerID ORDER BY sum(scorecard_batting_details.runs) DESC;',

	SELECT_CURRENT_BOWLING_DETAILS : 'SELECT PlayerID as id, players.PlayerFName as first_name, players.PlayerLName as last_name, picture as photo, isactive as is_active, sum(scorecard_bowling_details.overs) as overs, sum(scorecard_bowling_details.maidens) as maidens, sum(scorecard_bowling_details.runs) as runs, sum(scorecard_bowling_details.wickets) as wickets, sum(scorecard_bowling_details.noballs) as no_balls, sum(scorecard_bowling_details.wides) as wides FROM scorecard_bowling_details INNER JOIN players ON players.PlayerID = scorecard_bowling_details.player_id WHERE player_id in (SELECT PlayerID as id FROM players WHERE PlayerTeam = ?) AND season in (SELECT SeasonID FROM seasons WHERE SeasonYear = YEAR(CURDATE())) GROUP BY PlayerID ORDER BY sum(scorecard_bowling_details.wickets) DESC;',

	SELECT_BATTING_DETAILS_BY_SEASON : 'SELECT PlayerID as id, players.PlayerFName as first_name, players.PlayerLName as last_name, picture as photo, isactive as is_active, COUNT(runs) as innings, SUM(notout) as not_out, SUM(scorecard_batting_details.runs) as runs, sum(scorecard_batting_details.balls) as balls, MAX(runs) as highest, COUNT(CASE WHEN scorecard_batting_details.runs >= 100 THEN scorecard_batting_details.runs END) as hundreds, COUNT(CASE WHEN scorecard_batting_details.runs >= 50 AND scorecard_batting_details.runs < 100 THEN scorecard_batting_details.runs END) as fifties,  sum(scorecard_batting_details.fours) as fours, sum(scorecard_batting_details.sixes) as sixes FROM scorecard_batting_details INNER JOIN players ON players.PlayerID = scorecard_batting_details.player_id WHERE player_id in (SELECT PlayerID as id FROM players WHERE PlayerTeam = ?) AND season = ? GROUP BY PlayerID ORDER BY sum(scorecard_batting_details.runs) DESC;',

	SELECT_BOWLING_DETAILS_BY_SEASON : 'SELECT PlayerID as id, players.PlayerFName as first_name, players.PlayerLName as last_name, picture as photo, isactive as is_active, sum(scorecard_bowling_details.overs) as overs, sum(scorecard_bowling_details.maidens) as maidens, sum(scorecard_bowling_details.runs) as runs, sum(scorecard_bowling_details.wickets) as wickets, sum(scorecard_bowling_details.noballs) as no_balls, sum(scorecard_bowling_details.wides) as wides FROM scorecard_bowling_details INNER JOIN players ON players.PlayerID = scorecard_bowling_details.player_id WHERE player_id in (SELECT PlayerID as id FROM players WHERE PlayerTeam = ?) AND season = ? GROUP BY PlayerID ORDER BY sum(scorecard_bowling_details.wickets) DESC;',

	//SELECT_BATTING_DETAILS : 'SELECT PlayerID as id, players.PlayerFName as first_name, players.PlayerLName as last_name, picture as photo, sum(scorecard_batting_details.runs) as runs, sum(scorecard_batting_details.balls) as balls, sum(scorecard_batting_details.fours) as fours, sum(scorecard_batting_details.sixes) as sixes FROM scorecard_batting_details INNER JOIN players ON players.PlayerID = scorecard_batting_details.player_id WHERE player_id = ?;',

	//SELECT_BOWLING_DETAILS : 'SELECT PlayerID as id, players.PlayerFName as first_name, players.PlayerLName as last_name, picture as photo, sum(scorecard_bowling_details.overs) as overs, sum(scorecard_bowling_details.maidens) as maidens, sum(scorecard_bowling_details.runs) as runs, sum(scorecard_bowling_details.wickets) as wickets, sum(scorecard_bowling_details.noballs) as no_balls, sum(scorecard_bowling_details.wides) as wides FROM scorecard_bowling_details INNER JOIN players ON players.PlayerID = scorecard_bowling_details.player_id WHERE player_id = ?;',

	//SELECT_BATTING_DETAILS_BY_SEASON : 'SELECT PlayerID as id, players.PlayerFName as first_name, players.PlayerLName as last_name, picture as photo, sum(scorecard_batting_details.runs) as runs, sum(scorecard_batting_details.balls) as balls, sum(scorecard_batting_details.fours) as fours, sum(scorecard_batting_details.sixes) as sixes FROM scorecard_batting_details INNER JOIN players ON players.PlayerID = scorecard_batting_details.player_id WHERE player_id = ? AND season = ?;',

	//SELECT_BOWLING_DETAILS_BY_SEASON : 'SELECT PlayerID as id, players.PlayerFName as first_name, players.PlayerLName as last_name, picture as photo, sum(scorecard_bowling_details.overs) as overs, sum(scorecard_bowling_details.maidens) as maidens, sum(scorecard_bowling_details.runs) as runs, sum(scorecard_bowling_details.wickets) as wickets, sum(scorecard_bowling_details.noballs) as no_balls, sum(scorecard_bowling_details.wides) as wides FROM scorecard_bowling_details INNER JOIN players ON players.PlayerID = scorecard_bowling_details.player_id WHERE player_id = ? AND season = ?;',
}